# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDWzgXj2uo4L4JEYvuXYLjFYi-OIyqA3
"""

import streamlit as st
import pandas as pd
import pickle
import numpy as np

# --- 1. Konfigurasi Halaman Streamlit ---
st.set_page_config(page_title="Prediksi Daerah Rawan/Aman", layout="centered")
st.title("Sistem Prediksi Daerah Rawan/Aman (KNN)")
st.write("Aplikasi ini memprediksi apakah suatu daerah dikategorikan 'Rawan' atau 'Aman' berdasarkan data numerik yang diinput.")
st.markdown("---")

# --- 2. Load Model dan Scaler ---
model = None
scaler = None

try:
    # Memuat Model KNN (model.sav)
    with open('model.sav', 'rb') as model_file:
        model = pickle.load(model_file)

    # Memuat StandardScaler (scaler.sav) - PENTING untuk preprocessing
    with open('scaler.sav', 'rb') as scaler_file:
        scaler = pickle.load(scaler_file)

    st.sidebar.success("Model dan Scaler berhasil dimuat!")
except FileNotFoundError:
    st.error("ERROR: File 'model.sav' atau 'scaler.sav' tidak ditemukan.")
    st.warning("Pastikan kedua file tersebut berada di direktori yang sama dengan 'app.py' dan telah Anda buat di UAS.ipynb.")
except Exception as e:
    st.error(f"Terjadi kesalahan saat memuat file: {e}")

# --- 3. Input Pengguna (Sesuaikan dengan Fitur Training Anda) ---
st.header("Input Data Daerah")

if model is not None and scaler is not None:

    # Input utama: Asumsi 'Jumlah' adalah salah satu fitur kunci
    jumlah = st.number_input(
        "Masukkan Nilai untuk Fitur 'Jumlah' (e.g., Jumlah Kasus):",
        min_value=0,
        max_value=1000,
        value=50,
        step=1
    )

    # ----------------------------------------------------------------------
    # Hapus tanda komentar (uncomment) dan ganti nama variabel/label jika Anda
    # menggunakan fitur tambahan saat melatih model.
    # ----------------------------------------------------------------------
    # fitur_tambahan = st.number_input(
    #     "Masukkan Nilai untuk Fitur Tambahan (e.g., Kepadatan Penduduk):",
    #     min_value=0.0,
    #     value=100.0,
    #     step=0.1
    # )

    # Kumpulkan input dalam DataFrame (Pastikan urutan kolom sesuai urutan fitur saat training)
    data_input = pd.DataFrame([[jumlah]], columns=['Jumlah'])
    # Jika menggunakan 2 fitur:
    # data_input = pd.DataFrame([[jumlah, fitur_tambahan]], columns=['Jumlah', 'Kepadatan'])


    # Tombol Prediksi
    if st.button("Lakukan Prediksi"):

        # --- 4. Preprocessing dan Prediksi ---

        # 1. Scaling data input menggunakan scaler yang telah dimuat
        scaled_input = scaler.transform(data_input)

        # 2. Prediksi menggunakan model KNN
        prediction = model.predict(scaled_input)

        # --- 5. Tampilkan Hasil ---
        st.markdown("---")
        st.subheader("Hasil Klasifikasi")

        hasil_prediksi = prediction[0]

        if hasil_prediksi == "Daerah Rawan":
            st.error(f"Prediksi: **{hasil_prediksi}** ⚠️")
            st.write("Daerah ini diklasifikasikan sebagai **Daerah Rawan**. Diperlukan tindakan pencegahan.")
        elif hasil_prediksi == "Daerah Aman":
            st.success(f"Prediksi: **{hasil_prediksi}** ✅")
            st.write("Daerah ini diklasifikasikan sebagai **Daerah Aman**. Tetap waspada.")
        else:
            st.info(f"Hasil prediksi: **{hasil_prediksi}**")